# Generated by Django 3.2.4 on 2021-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
